export const SERVER_PORT = 'SERVER_PORT'
export const DDB_HOST = 'DDB_HOST'
export const DB_PORT = 'DB_PORT'
export const DB_USERNAME = 'DB_USERNAME'
export const DB_PASSWORD = 'DB_PASSWORD'
export const DB_NAME = 'DB_NAME'
export const JWT_SECRET = 'JWT_SECRET'